### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by mpaiva** [muqueca/mpendergast#1]
same as old site

**Comment by mpaiva** [comment]
![image](https://user-images.githubusercontent.com/781670/36279135-19fd209a-1264-11e8-8166-5a93e7f4e3fe.png)

**Comment by mpaiva** [comment]
Add Sellers and Buyers to the Nav

**Comment by mpaiva** [comment]
incorporate these sub-menu items

![image](https://user-images.githubusercontent.com/781670/36279192-4acfaa3a-1264-11e8-9257-d0fd20231df3.png)

**Comment by mpaiva** [comment]
![image](https://user-images.githubusercontent.com/781670/36279225-6488f346-1264-11e8-8e4c-3ff32d31fa29.png)

**Comment by MarcelloPaiva** [comment]
Finished creating the Navigation
